name: Update GitHub Snake

on:
  schedule:
    - cron: '0 0 * * *' # executa todo dia à meia-noite
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update snake
        uses: platane/snk@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit updated snake
        run: git commit -am "Update snake" || echo "No changes to commit"
